### PR TITLE
Small refactoring to improve readability and ease future changes. 

### PR DESCRIPTION
**Pull request by hhugo**

### CODE REVIEW

**Comment by hhugo** [comment]
> Looks great. Do you want to incorporate the changes to make `from_stream` use `from_gen` while we're at it?

I don't know what you're referring to

**Comment by toots** [comment]
> > Looks great. Do you want to incorporate the changes to make `from_stream` use `from_gen` while we're at it?
> 
> I don't know what you're referring to

This PR: https://github.com/ocaml-community/sedlex/pull/131

**Comment by hhugo** [comment]
(I think the scope of #131 should be extended a bit to include utf16 and from_int_array)

**Comment by hhugo** [comment]
@toots, I've just rebased this PR.
Can we merge ?

**Comment by toots** [comment]
> @toots, I've just rebased this PR. Can we merge ?

Sure. Do we need to include an entry in the changelog for it?

**Comment by hhugo** [comment]
> > @toots, I've just rebased this PR. Can we merge ?
> 
> Sure. Do we need to include an entry in the changelog for it?

I don't think so, there is no change of behavior. Just minor refactoring

**Pull request merged**
