### PR TITLE
upgrade to dune, opam >= 2.0

### PR DESCRIPTION
**Pull request by smolkaj**
This upgrades the project to dune and opam 2.0.

We should also release a new version of sedlex on opam. The [current release](https://opam.ocaml.org/packages/sedlex/) has the (spurious?) constraint
```
    ppx_tools_versioned < 5.2.1
```
which makes sedlex incompatible with tons of other libraries (e.g., the Jane Street libraries).

### CODE REVIEW

**Comment by pmetzger** [comment]
LGTM. Lets see what Travis says...

**Comment by smolkaj** [comment]
Looks like Travis is happy!
Once this is merged in, do you want to do the release or should I take care of it? (I would probably need write access.)

**Comment by pmetzger** [comment]
@smolkaj I can give you access as a contributor if you wish.

**Comment by pmetzger** [comment]
(And sorry about the slow turnaround time; all the more reason to make you a contributor...)

**Comment by smolkaj** [comment]
Thanks for the merge!
Sounds great. Then I will do an opam release.

**Comment by pmetzger** [comment]
@smolkaj You should have an invite to be a collaborator now.

**Pull request merged**
