### PR TITLE
Check and fix Sedlex_cset invariant

### LINKED ISSUE #143: Sedlex_cset invariant not respected
inside 
- `Sedlex_cset.tr8876_ident_char`
- `Unicode.{Categories,Properties}`

### PR DESCRIPTION
**Pull request by hhugo**
fix #143

### CODE REVIEW

**Review by toots — COMMENTED** [review]
The changes and reorganization look great. I'll need another pass at the code for this one.

Could you clarify what you mean by check and fix invariant in the changelog at least? Otherwise it seems that the entry wouldn't be very informative to the library's user.

Thnks!

**Comment by hhugo** [comment]
I've completed the Changelog

**Review by toots — APPROVED** [review]
This looks good to me.

Long term (and possibly the next PR): do you know if we need to pay attention to the ISO and xml file for updating? Do they overlap with some of the automatically extracted character sets from `unicode.ml`? Can we add more automatically extracted character sets?

**Comment by hhugo** [comment]
> This looks good to me.
> 
> Long term (and possibly the next PR): do you know if we need to pay attention to the ISO and xml file for updating? Do they overlap with some of the automatically extracted character sets from `unicode.ml`? Can we add more automatically extracted character sets?

I know nothing about the predefined cset and I couldn't find anyting useful regarding the iso tr8876_ident_char.

**Comment by hhugo** [comment]
Can this be merged ? Or do you want more review/work ?

**Comment by toots** [comment]
> Can this be merged ? Or do you want more review/work ?

Sorry I didn't realize that you may not be able to merge? Once I approve, this means it can be merged any time..

**Pull request merged**
